[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "two_step_nuc"
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.20.0"
]

[tool.maturin]
features = ["python"]
python-source = "python"
